server:
  servlet:
    context-path: /
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jira?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jira
    password: jira12!
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true
